
from MDL.Person import Person as MDL_Person_Person

# Generated by mdl_generate_python_code.py / 2005/07/12 17:25
from Modeling.Validation import ValidationException
from mx.DateTime import DateTimeFrom

from model import Model

class Person(Model, MDL_Person_Person): 
  """
  Persons are objects ...
  """
  
  def __init__(self, **kw):
    "Initializer"
    # Note: if you modify this method, it is a strong requirement that
    # every parameter gets a default value, since the framework needs to be
    # able to instanciate an object with no parameter at all.
    # MDL_Person_Person.__init__(self)
    super(Person, self).__init__()
    for k,v in kw.items():
      self.takeValueForKey(v, k)

  def validateName(self, value):
    "Edit this to enforce custom business logic"
    if 0: # your custom bizlogic
      raise ValidationException
    return

  def validateSurname(self, value):
    "Edit this to enforce custom business logic"
    if 0: # your custom bizlogic
      raise ValidationException
    return

 
