
from MDL.Product import Product as MDL_Product_Product

# Generated by mdl_generate_python_code.py / 2005/07/07 18:51
from Modeling.Validation import ValidationException
from mx.DateTime import DateTimeFrom

from model import Model

import logging
logger = logging.getLogger('fvl.luca')
logger.setLevel(logging.DEBUG)

class Product(Model, MDL_Product_Product): 
  """
  Products are objects ...
  """
  def __init__(self, **kw):
    "Initializer"
    # Note: if you modify this method, it is a strong requirement that
    # every parameter gets a default value, since the framework needs to be
    # able to instanciate an object with no parameter at all.
    # MDL_Product_Product.__init__(self)
    super(Product, self).__init__()
    for k,v in kw.items():
      self.takeValueForKey(v, k)

  def validateCode(self, value):
    "Edit this to enforce custom business logic"
    if 0: # your custom bizlogic
      raise ValidationException
    return

  def validateName(self, value):
    "Edit this to enforce custom business logic"
    if 0: # your custom bizlogic
      raise ValidationException
    return
