
from MDL.Stock import Stock as MDL_Stock_Stock

# Generated by mdl_generate_python_code.py / 2005/07/07 18:51
from Modeling.Validation import ValidationException
from mx.DateTime import DateTimeFrom

from model import Model

import logging
logger = logging.getLogger('fvl.luca.model.stock')
# logger.setLevel(logging.DEBUG)

class Stock(Model, MDL_Stock_Stock): 
  """
  Stocks are objects ...
  """
  
  def __init__(self, **kw):
    "Initializer"
    # Note: if you modify this method, it is a strong requirement that
    # every parameter gets a default value, since the framework needs to be
    # able to instanciate an object with no parameter at all.
    #MDL_Stock_Stock.__init__(self)
    super(Stock, self).__init__()
    for k,v in kw.items():
      self.takeValueForKey(v, k)

  def validateLevel(self, value):
    "Edit this to enforce custom business logic"
    if 0: # your custom bizlogic
      raise ValidationException
    return

  def validateProduct(self, value):
    "Edit this to enforce custom business logic"
    if 0: # your custom bizlogic
      raise ValidationException
    return
